# Generated by Django 4.1.3 on 2022-12-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo_front', models.FileField(upload_to='user-passports/')),
                ('passport_photo_back', models.FileField(upload_to='user-passports/')),
                ('car_passport_front', models.FileField(upload_to='car-passports/')),
                ('car_passport_back', models.FileField(upload_to='car-passports/')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='car.carinfo')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
