# Generated by Django 4.1.3 on 2022-12-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdocument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
