# Generated by Django 4.1.3 on 2023-11-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('userdocument', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='car.carinfo', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='car_passport_back',
            field=models.FileField(upload_to='car-passports/', verbose_name='Свидетелесьтво о регистраций ТС (обратная сторона)'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='car_passport_front',
            field=models.FileField(upload_to='car-passports/', verbose_name='Свидетелесьтво о регистраций ТС (тех. паспорт)'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='passport_photo_back',
            field=models.FileField(upload_to='user-passports/', verbose_name='Водительское удостоверение (обратная сторона)'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='passport_photo_front',
            field=models.FileField(upload_to='user-passports/', verbose_name='Водительское удостоверение (лицевая сторона)'),
        ),
    ]
