# Generated by Django 4.0.6 on 2022-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'registered'), ('requested_to_driver', 'requested_to_driver'), ('allowed_drive', 'allowed_drive'), ('disallowed_drive', 'disallowed_drive')], default='registered', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
