# Generated by Django 4.0.6 on 2022-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driver_can_view_order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
