# Generated by Django 4.0.6 on 2022-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_driver_can_view_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
