# Generated by Django 4.0.6 on 2022-10-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cititocityprice'),
        ('users', '0009_profileinfo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='driver_can_view_order_date',
        ),
        migrations.CreateModel(
            name='CityToCityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_can_view_order_date', models.DateField(blank=True, null=True)),
                ('city_to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cititocityprice')),
            ],
        ),
    ]
