# Generated by Django 4.0.6 on 2022-10-07 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_driver_can_view_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citytocityorder',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
