# Generated by Django 4.0.6 on 2022-10-10 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citytocityorder',
            name='coin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
