# Generated by Django 4.0.6 on 2022-11-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_payment_gen_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeuser',
            options={'verbose_name': 'Цена заказа', 'verbose_name_plural': 'Цены заказа'},
        ),
        migrations.AddField(
            model_name='profile',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен Firebase'),
        ),
    ]
