# Generated by Django 4.1.3 on 2023-01-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='form-images/')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
