# Generated by Django 4.1.3 on 2023-01-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_feedbackform_delete_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackForm',
            new_name='FeedBack',
        ),
    ]
