# Generated by Django 4.1.3 on 2022-11-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_userdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityToCityOrder',
        ),
    ]
