# Generated by Django 4.1.3 on 2023-11-19 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_city_region'),
        ('users', '0002_payment_paid_at_payment_payment_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователе'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата присоединения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Получил статус?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='Телефон пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('requested_to_driver', 'Запрос от водителя'), ('allowed_drive', 'Разрешено водить'), ('disallowed_drive', 'Недопущено к управлению')], default='registered', max_length=255, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.typeuser', verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День рождение'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='regions.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
