# Generated by Django 4.0.6 on 2022-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_citytocityorder_coin_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gen_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
