# Generated by Django 4.0.6 on 2022-11-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_city_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Городы'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
