# Generated by Django 4.1.3 on 2022-11-28 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_citytocityorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_from', to='regions.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to', to='regions.city')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
        migrations.CreateModel(
            name='AccessOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField()),
                ('can_access_date', models.DateField(blank=True, null=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_orders', to='order.access')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CitiToCityPrice',
        ),
    ]
