# Generated by Django 4.1.3 on 2023-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_coin', models.IntegerField(verbose_name='Цена по умолчанию для городов')),
            ],
        ),
    ]
