# Generated by Django 4.1.3 on 2022-11-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_access_accessorder_delete_cititocityprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorder',
            name='access',
        ),
        migrations.RemoveField(
            model_name='accessorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='AccessOrder',
        ),
    ]
