# Generated by Django 4.0.6 on 2022-10-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_city_status'),
        ('order', '0003_alter_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiToCityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.IntegerField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_price', to='regions.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_price', to='regions.city')),
            ],
        ),
    ]
