# Generated by Django 4.1.3 on 2022-12-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0001_initial'),
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_from', to='regions.city'),
        ),
        migrations.AddField(
            model_name='access',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to', to='regions.city'),
        ),
    ]
