# Generated by Django 4.1.3 on 2023-11-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessorder',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_orders', to='access.access'),
        ),
    ]
