# Generated by Django 4.1.3 on 2023-11-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_city_region'),
        ('access', '0003_alter_accessorder_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='coin',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='access',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_from', to='regions.city', verbose_name='От города'),
        ),
        migrations.AlterField(
            model_name='access',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_to', to='regions.city', verbose_name='До города'),
        ),
    ]
