# Generated by Django 4.1.2 on 2022-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telemetry', '0002_telegramchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='chat_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
