# Generated by Django 4.1.2 on 2022-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telemetry', '0003_alter_telegramchat_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
