# Generated by Django 4.0.6 on 2022-11-15 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cititocityprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cititocityprice',
            options={'verbose_name': 'Цена заказа', 'verbose_name_plural': 'Цены заказа'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='typeorder',
            options={'verbose_name': 'Тип заказа', 'verbose_name_plural': 'Типы заказа'},
        ),
    ]
