name: Taxi Back Pre-Release
run-name: ${{ github.actor }} building and deploying  🚀
on:
  push:
    branches: ['release']
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r req.txt
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: "195.49.215.203"
          username: "ubuntu"
          password: "esr3Pcafhq(p"
          port: "22"
          script: |
            cd taxiback
            git pull
            docker-compose up -d --build
